name: Build and lint

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 0" # Every sunday at 3am UTC.

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: NodeJS version
        run: node -v
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
