name: Changelog
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  updateChangelog:
    name: Update changelog
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        repo: ["EventStore-Client-NodeJS"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update changelog for the ${{ matrix.repo }} repo
        uses: w1am/Automations/changelog-update@master
        with:
          github-token: ${{ secrets.GH_PAT }}
          mode: batch
          owner: w1am
          repo: ${{ matrix.repo }}