name: tests workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      eventstore_cloud_id:
        required: false
      tailscale_auth:
        required: false

jobs:
  build-and-test:
    name: "${{ matrix.group.name }}"
    strategy:
      fail-fast: false
      matrix:
        group:
          - name: projections
            path: ./src/projections
    env:
      # Github only passes secrets to the main repo, so we need to skip some things if they are unavailable
      SECRETS_AVAILABLE: ${{ secrets.eventstore_cloud_id != null }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .github/files/.nvmrc
      - name: NodeJS version
        run: node -v
      - name: Install
        run: yarn
      - name: Build 
        run: yarn build
      - name: Run Tests
        run: yarn test ${{ matrix.group.path }} --ci --run-in-band --forceExit
        env:
          EVENTSTORE_IMAGE: eventstore-ce:${{ inputs.version }}
          EVENTSTORE_CLOUD_ID: ${{ secrets.eventstore_cloud_id }}
